

// *** Code author: Argent77 ***

// bs2
PRINT @07 

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btbs2.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
   // ACTION_IF (success) BEGIN //
	ACTION_IF (NOT success) BEGIN
	//// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	// //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// cla

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btcla.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0004.pvrz~ ~MOS0005.pvrz~ ~MOS0006.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
	ACTION_IF (NOT success) BEGIN
	 //PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// def

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btdef.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0007.pvrz~ ~MOS0008.pvrz~ ~MOS0009.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// med

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btmed.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0034.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// lin

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btlin.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0025.pvrz~ ~MOS0026.pvrz~ ~MOS0027.pvrz~ ~MOS0028.pvrz~ ~MOS0029.pvrz~ ~MOS0030.pvrz~ ~MOS0031.pvrz~ ~MOS0032.pvrz~ ~MOS0033.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// law

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btlaw.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0016.pvrz~ ~MOS0017.pvrz~ ~MOS0018.pvrz~ ~MOS0019.pvrz~ ~MOS0020.pvrz~ ~MOS0021.pvrz~ ~MOS0022.pvrz~ ~MOS0023.pvrz~ ~MOS0024.pvrz~   BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// sdb

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btsdb.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0045.pvrz~ ~MOS0046.pvrz~ ~MOS0047.pvrz~ ~MOS0048.pvrz~ ~MOS0049.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// shd

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btshd.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0053.pvrz~ ~MOS0054.pvrz~ ~MOS0055.pvrz~ ~MOS0056.pvrz~ ~MOS0057.pvrz~ ~MOS0058.pvrz~ ~MOS0059.pvrz~ ~MOS0060.pvrz~ ~MOS0061.pvrz~ ~MOS0062.pvrz~  ~MOS0063.pvrz~ ~MOS0064.pvrz~ ~MOS0065.pvrz~ ~MOS0066.pvrz~ ~MOS0067.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// pos

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btpos.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0038.pvrz~ ~MOS0039.pvrz~ ~MOS0040.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
/*
// ton

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btton.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0068.pvrz~ ~MOS0069.pvrz~ ~MOS0070.pvrz~ ~MOS0071.pvrz~ ~MOS0072.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
*/
// jnw

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btjnw.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0010.pvrz~ ~MOS0011.pvrz~ ~MOS0012.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// jol

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btjol.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0013.pvrz~ ~MOS0014.pvrz~ ~MOS0015.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// por

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btpor.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0035.pvrz~ ~MOS0036.pvrz~ ~MOS0037.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// sd1

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btsd1.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0041.pvrz~ ~MOS0042.pvrz~ ~MOS0043.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// sh1

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btsh1.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0050.pvrz~ ~MOS0051.pvrz~ ~MOS0052.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
/*
// ttn

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btttn.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0073.pvrz~ ~MOS0074.pvrz~ ~MOS0075.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
*/
// que

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/copy/mos+pvrz/g-btque.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS99639.pvrz~ ~MOS99640.pvrz~ ~MOS99641.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/copy/mos+pvrz/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

PRINT @09